[package]
name = "job-processor"
version = "0.1.0"
edition = "2024"

[dependencies]
actix-web = "4"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0"
validator = { version = "0.18", features = ["derive"] }
actix-web-validator = "6.0"
